<a href="https://colab.research.google.com/github/CaseySobon/Recommendation-system/blob/main/Recommendations_with_ensomble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# innstall java
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

# install spark (change the version number if needed)
!wget -q https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz

# unzip the spark file to the current folder
!tar xf spark-3.2.1-bin-hadoop3.2.tgz

# set your spark folder to your system path environment.
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.2.1-bin-hadoop3.2"


# install findspark using pip
!pip install -q findspark

In [ ]:
import findspark

findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

from google.colab import files

In [ ]:
import pandas as pd
import numpy as np
from pyspark.mllib.linalg.distributed import *
from pyspark.sql import functions as f
from pyspark.sql.functions import when,concat_ws
from pyspark.sql.window import *
from pyspark.sql.functions import row_number

In [ ]:
s_1 = spark.read.csv('cvgbtree_84392.csv', header = True, inferSchema = True)
s_1 = s_1.select('TrackID','Predictor').withColumnRenamed('Predictor','s1')

s_2 = spark.read.csv('dtree_56969.csv', header = True, inferSchema = True)
s_2 = s_2.select('TrackID','Predictor').withColumnRenamed('Predictor','s2')

S =s_1.join(s_2, ['TrackID'],'left').orderBy('TrackID')

s_3 = spark.read.csv('dtree_57003.csv', header = True, inferSchema = True)
s_3 = s_3.select('TrackID','Predictor').withColumnRenamed('Predictor','s3')

S =S.join(s_3, ['TrackID'],'left').orderBy('TrackID')

s_4 = spark.read.csv('gbtree2_83400.csv', header = True, inferSchema = True)
s_4 = s_4.select('TrackID','Predictor').withColumnRenamed('Predictor','s4')

S =S.join(s_4, ['TrackID'],'left').orderBy('TrackID')

s_5 = spark.read.csv('gbtree_59588.csv', header = True, inferSchema = True)
s_5 = s_5.select('TrackID','Predictor').withColumnRenamed('Predictor','s5')

S =S.join(s_5, ['TrackID'],'left').orderBy('TrackID')

s_6 = spark.read.csv('linear_53983.csv', header = True, inferSchema = True)
s_6 = s_6.select('TrackID','Predictor').withColumnRenamed('Predictor','s6')

S =S.join(s_6, ['TrackID'],'left').orderBy('TrackID')

s_7 = spark.read.csv('linear_56568.csv', header = True, inferSchema = True)
s_7 = s_7.select('TrackID','Predictor').withColumnRenamed('Predictor','s7')

S =S.join(s_7, ['TrackID'],'left').orderBy('TrackID')

s_8 = spark.read.csv('p1_84411.csv', header = True, inferSchema = True)
s_8 = s_8.select('TrackID','Predictor').withColumnRenamed('Predictor','s8')

S =S.join(s_8, ['TrackID'],'left').orderBy('TrackID')

s_9 = spark.read.csv('p2_84044.csv', header = True, inferSchema = True)
s_9 = s_9.select('TrackID','Predictor').withColumnRenamed('Predictor','s9')

S =S.join(s_9, ['TrackID'],'left').orderBy('TrackID')

s_10 = spark.read.csv('rforest2_84392.csv', header = True, inferSchema = True)
s_10 = s_10.select('TrackID','Predictor').withColumnRenamed('Predictor','s10')

S =S.join(s_10, ['TrackID'],'left').orderBy('TrackID')

s_11 = spark.read.csv('rforest_61804.csv', header = True, inferSchema = True)
s_11 = s_11.select('TrackID','Predictor').withColumnRenamed('Predictor','s11')

S =S.join(s_11, ['TrackID'],'left').orderBy('TrackID')

s_12 = spark.read.csv('sprk1_52909.csv', header = True, inferSchema = True)
s_12 = s_12.select('TrackID','Predictor').withColumnRenamed('Predictor','s12')

S =S.join(s_12, ['TrackID'],'left').orderBy('TrackID')

s_13 = spark.read.csv('sprk2_24975.csv', header = True, inferSchema = True)
s_13 = s_13.select('TrackID','Predictor').withColumnRenamed('Predictor','s13')

S =S.join(s_13, ['TrackID'],'left').orderBy('TrackID')

s_14 = spark.read.csv('sprk2_69438.csv', header = True, inferSchema = True)
s_14 = s_14.select('TrackID','Predictor').withColumnRenamed('Predictor','s14')

S =S.join(s_14, ['TrackID'],'left').orderBy('TrackID')

s_15 = spark.read.csv('sprk3_80276.csv', header = True, inferSchema = True)
s_15 = s_15.select('TrackID','Predictor').withColumnRenamed('Predictor','s15')

S =S.join(s_15, ['TrackID'],'left').orderBy('TrackID')

s_16 = spark.read.csv('sprk_60536.csv', header = True, inferSchema = True)
s_16 = s_16.select('TrackID','Predictor').withColumnRenamed('Predictor','s16')

S =S.join(s_16, ['TrackID'],'left').orderBy('TrackID')

S.show(5)


+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|      TrackID| s1| s2| s3| s4| s5| s6| s7| s8| s9|s10|s11|s12|s13|s14|s15|s16|
+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|199810_105760|  1|  0|  0|  1|  1|  1|  1|  1|  1|  1|  0|  0|  0|  0|  1|  1|
| 199810_18515|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1|  0|  0|  1|  0|
|199810_208019|  1|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  0|  1|  1|  0|  0|
|199810_242681|  0|  1|  0|  0|  0|  1|  1|  0|  0|  0|  1|  1|  0|  0|  0|  1|
| 199810_74139|  0|  1|  1|  0|  0|  0|  0|  1|  1|  1|  1|  1|  1|  1|  1|  1|
+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
only showing top 5 rows



In [ ]:
P = np.array([0.84392,0.56969,0.75003,0.83400,0.59588,0.53983,0.56568,0.84411,0.84044,0.84392,0.61804,0.52909,0.24975,0.69438,0.80276,0.60536])
print(len(P))

summ = np.mean(P)

print(summ)

16
0.6704300000000001


In [ ]:
Sd = S.na.replace(0, -1) # submission results
Sd.show(5)

+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|      TrackID| s1| s2| s3| s4| s5| s6| s7| s8| s9|s10|s11|s12|s13|s14|s15|s16|
+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
|199810_105760|  1| -1| -1|  1|  1|  1|  1|  1|  1|  1| -1| -1| -1| -1|  1|  1|
| 199810_18515|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1|  1| -1| -1|  1| -1|
|199810_208019|  1| -1| -1| -1| -1| -1| -1| -1| -1| -1| -1| -1|  1|  1| -1| -1|
|199810_242681| -1|  1| -1| -1| -1|  1|  1| -1| -1| -1|  1|  1| -1| -1| -1|  1|
| 199810_74139| -1|  1|  1| -1| -1| -1| -1|  1|  1|  1|  1|  1|  1|  1|  1|  1|
+-------------+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
only showing top 5 rows



AttributeError: ignored

In [ ]:
N = 120000 #total number of tracks

STx = N*((2*P)-1)
print(STx)

[ 82540.8  16725.6  60007.2  80160.   23011.2   9559.2  15763.2  82586.4
  81705.6  82540.8  28329.6   6981.6 -60060.   46651.2  72662.4  25286.4]


In [ ]:
Spd = Sd.toPandas()
Spd = Spd[['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14', 's15', 's16']].values

print(Spd)

[[ 1 -1 -1 ... -1  1  1]
 [ 1  1  1 ... -1  1 -1]
 [ 1 -1 -1 ...  1 -1 -1]
 ...
 [-1  1 -1 ...  1 -1 -1]
 [-1 -1  1 ...  1 -1  1]
 [-1 -1 -1 ...  1 -1 -1]]


In [ ]:

Sm = np.dot(Spd.T, Spd)

print(Sm)

[[120000  18276  15176  98548  22744   9348  15812  75784  82288 100656
   27236  10164 -59280 -59280  75136  26472]
 [ 18276 120000  27828  16388  38800  19516  22732  18596  18068  18460
   43604   4084 -14388 -14388  13616  12312]
 [ 15176  27828 120000  14604  42740  10620  13520  13580  14776  15220
   36600   4696  -9388  -9388  12780   8560]
 [ 98548  16388  14604 120000  21936   9124  15420  73868  79068  94504
   26432   9356 -57712 -57712  72968  25524]
 [ 22744  38800  42740  21936 120000  22452  24136  21312  22072  22608
   65748   6152 -15268 -15268  20256  13568]
 [  9348  19516  10620   9124  22452 120000  57496  13988  13728   9272
   24064  -9468  -5368  -5368  13444   3544]
 [ 15812  22732  13520  15420  24136  57496 120000  20004  19572  16288
   32864   4340 -11088 -11088  18736  15920]
 [ 75784  18596  13580  73868  21312  13988  20004 120000  94872  76016
   27732   7052 -62224 -62224  72460  22912]
 [ 82288  18068  14776  79068  22072  13728  19572  94872 120000

In [ ]:
S_inv = np.linalg.inv(Sm)

print(S_inv)

[[ 1.48615048e-05 -6.60158378e-07 -1.48382077e-07 -1.61798965e-05
  -1.62006071e-07  8.63599154e-08  7.13379910e-07 -1.16044097e-06
  -5.95300687e-06 -4.04214340e-06 -2.01400981e-06 -5.86440592e-07
   1.26292781e+11 -1.26292781e+11  1.17814201e-05  0.00000000e+00]
 [-4.61690055e-06  1.01012331e-05 -1.04169974e-06 -3.86404942e-06
  -1.40695720e-06 -4.49049812e-07 -5.60553445e-07 -2.88434730e-07
  -3.16159699e-06  1.69659509e-05 -2.36422250e-06 -1.83036723e-07
   1.84311500e+10 -1.84311500e+10  3.55432699e-06  0.00000000e+00]
 [ 8.65939757e-07 -9.93920710e-07  9.87370121e-06  6.27045671e-07
  -2.44659732e-06  6.60553715e-08 -1.01273030e-07  8.83275112e-08
  -4.02026712e-07  3.30853573e-07 -1.21866628e-06 -9.44810106e-08
  -5.77711269e+09  5.77711269e+09 -9.87499656e-07  0.00000000e+00]
 [-8.43419329e-06  4.26937555e-07 -2.85557027e-07  2.39008430e-05
  -3.32627133e-07 -5.12128329e-08  1.94563686e-07 -1.94542765e-06
   3.06786312e-06  2.41609910e-05  3.35981352e-07 -5.35009606e-07
   7.94

In [ ]:
a = np.dot(S_inv,STx)

print(a)

[-1.34768542e+16 -1.96681014e+15  6.16482627e+14 -8.47353878e+15
 -1.12375610e+15  2.83546183e+15 -2.36770154e+15 -1.13113207e+16
 -1.19926017e+16 -4.00452854e+15 -2.41302912e+15 -1.93269714e+15
  4.38820717e+32 -4.38820717e+32 -5.78980326e+14  2.93325513e+16]


In [ ]:
ensoble = np.dot(Spd,a)
ensoble = ensoble.reshape(-1, 1)
ensoble=pd.DataFrame(ensoble)
print(ensoble)

                   0
0       2.783881e+16
1       1.644670e+16
2      -4.340041e+16
3       1.159789e+17
4      -8.245571e+16
...              ...
119995  1.907913e+16
119996  1.857479e+16
119997 -2.424572e+16
119998 -1.907913e+16
119999 -1.077578e+16

[120000 rows x 1 columns]


In [ ]:
Ss = Sd.select('TrackID').toPandas()
print(Ss)

              TrackID
0       199810_105760
1        199810_18515
2       199810_208019
3       199810_242681
4        199810_74139
...               ...
119995  249010_186634
119996  249010_262811
119997  249010_293818
119998   249010_72192
119999   249010_86104

[120000 rows x 1 columns]


In [ ]:
Sp = pd.concat([Ss,ensoble], axis=1)
Sp = spark.createDataFrame(Sp)
Sp = Sp.select("trackID","0").withColumnRenamed('0','Predictor')
Sp.show(16)

+-------------+--------------------+
|      trackID|           Predictor|
+-------------+--------------------+
|199810_105760|2.783880808321032...|
| 199810_18515|1.644670054600919...|
|199810_208019|-4.34004089568837...|
|199810_242681|1.159789353162734...|
| 199810_74139|-8.24557099429869...|
|  199810_9903|-3.44083250456222...|
|199812_130023| 2.81362527595824E16|
|199812_142408|2.031209482031181...|
|199812_211361|-2.03120948203118...|
|199812_223706|1.746124748881675...|
|199812_276940|-2.03120948203118...|
| 199812_29189|-2.52854054280873...|
|199813_111874|1.258809239315949...|
|199813_184173|-4.60978772591954...|
|199813_188441|4.344030485015414...|
| 199813_20968|-2.03120948203118...|
+-------------+--------------------+
only showing top 16 rows



In [ ]:
predict_f1=Sp.withColumn("Predictor", when(Sp.Predictor <= 3,0).otherwise(1))

predict_f1.show(50)
print((predict_f1.count(), len(predict_f1.columns)))

+-------------+---------+
|      trackID|Predictor|
+-------------+---------+
|199810_105760|        1|
| 199810_18515|        1|
|199810_208019|        0|
|199810_242681|        1|
| 199810_74139|        0|
|  199810_9903|        0|
|199812_130023|        1|
|199812_142408|        1|
|199812_211361|        0|
|199812_223706|        1|
|199812_276940|        0|
| 199812_29189|        0|
|199813_111874|        1|
|199813_184173|        0|
|199813_188441|        1|
| 199813_20968|        0|
| 199813_21571|        1|
| 199813_79640|        0|
|199814_122375|        0|
|199814_122429|        0|
|199814_189043|        1|
|199814_232332|        1|
|199814_262193|        0|
| 199814_52519|        1|
|199815_118841|        0|
|199815_129866|        1|
|199815_258473|        1|
|199815_275682|        1|
| 199815_30062|        0|
| 199815_64345|        0|
|199816_102153|        1|
|199816_183464|        0|
| 199816_23616|        1|
|199816_274758|        0|
| 199816_46627|        0|
| 199816_816

In [ ]:
predict_f1.toPandas().to_csv('ensoble1.csv',index=False)

In [ ]:

col_list = ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14', 's15', 's16']
df2 = S.withColumn('Predictor',sum([f.col(c) for c in col_list]))
summed = df2.select('TrackID','Predictor')
summed.show(16)

+-------------+---------+
|      TrackID|Predictor|
+-------------+---------+
|199810_105760|       10|
| 199810_18515|       13|
|199810_208019|        3|
|199810_242681|        6|
| 199810_74139|       11|
|  199810_9903|        5|
|199812_130023|        9|
|199812_142408|       13|
|199812_211361|        3|
|199812_223706|       11|
|199812_276940|        3|
| 199812_29189|        9|
|199813_111874|        4|
|199813_184173|       11|
|199813_188441|        9|
| 199813_20968|        5|
+-------------+---------+
only showing top 16 rows



In [ ]:
predict_f1=Sp.withColumn("Predictor", when(Sp.Predictor >= 4,1).otherwise(0))

predict_f1.show(50)
print((predict_f1.count(), len(predict_f1.columns)))

+-------------+---------+
|      trackID|Predictor|
+-------------+---------+
|199810_105760|        1|
| 199810_18515|        1|
|199810_208019|        0|
|199810_242681|        1|
| 199810_74139|        0|
|  199810_9903|        0|
|199812_130023|        1|
|199812_142408|        1|
|199812_211361|        0|
|199812_223706|        1|
|199812_276940|        0|
| 199812_29189|        0|
|199813_111874|        1|
|199813_184173|        0|
|199813_188441|        1|
| 199813_20968|        0|
| 199813_21571|        1|
| 199813_79640|        0|
|199814_122375|        0|
|199814_122429|        0|
|199814_189043|        1|
|199814_232332|        1|
|199814_262193|        0|
| 199814_52519|        1|
|199815_118841|        0|
|199815_129866|        1|
|199815_258473|        1|
|199815_275682|        1|
| 199815_30062|        0|
| 199815_64345|        0|
|199816_102153|        1|
|199816_183464|        0|
| 199816_23616|        1|
|199816_274758|        0|
| 199816_46627|        0|
| 199816_816

In [ ]:
predict_f1.toPandas().to_csv('summed.csv',index=False)